### ISSUE TITLE
苹果手机使用自定义顶部导航栏时会有一个很小的白边

### ISSUE THREAD

**Issue by DreamTom** [XiaokangLei/ColorUI-GA#22]
![image](https://github.com/XiaokangLei/ColorUI-GA/assets/50534983/bc0b63d6-c254-4049-8ab8-47b05bd4ccfa)
可以放大看看

**Comment by XiaokangLei** [comment]
> ![image](https://private-user-images.githubusercontent.com/50534983/289563114-bc0b63d6-c254-4049-8ab8-47b05bd4ccfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDE3NjksIm5iZiI6MTcwNDIwMTQ2OSwicGF0aCI6Ii81MDUzNDk4My8yODk1NjMxMTQtYmMwYjYzZDYtYzI1NC00MDQ5LThhYjgtNDdiMDViZDRjY2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEzMTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YzFmNGVjZWMyOGFhZTI2ZWEwYWIxYzdhMWIzNWEyYTE3OTljZTNiMDcwYmM5YTYyODJkNWNkN2FkNDgxNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WZ45zCM_Bi4RTXdi0UII3iOJJPcwzSE7Q8zKxZPZsD4) 可以放大看看

麻烦提供一下机型

**Comment by DreamTom** [comment]
iPhone12 iOS15.4.1

**Comment by hutaoseven** [comment]
可以尝试修改 main.wxss 中的样式
> 原样式
```css
.cu-custom .cu-bar {
  min-height: 0px;
  padding-right: 220rpx;
  box-shadow: 0rpx 0rpx 0rpx;
  z-index: 9999;
}
```
> 修改样式
```css
.cu-custom .cu-bar {
  min-height: 0;
  padding-right: 220rpx;
  box-shadow: 0;
  z-index: 9999;
}
```
